INSERT INTO tb_user (name, email, password) VALUES ('Bob', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Ana', 'ana@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_role (authority) VALUES ('ROLE_VISITOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_MEMBER');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);

INSERT INTO tb_genre (name) VALUES ('Comédia');
INSERT INTO tb_genre (name) VALUES ('Romance');
INSERT INTO tb_genre (name) VALUES ('Terror');
INSERT INTO tb_genre (name) VALUES ('Ação');
INSERT INTO tb_genre (name) VALUES ('Fantasia');

INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('A Torre Negra', null, 2017, 'https://www.themoviedb.org/t/p/w1280/t4IeczvPNloj3IrDm2NjALKMV01.jpg','Um pistoleiro chamado Roland Deschain (Idris Elba) percorre o mundo em busca da famosa Torre Negra, prédio mágico que está prestes a desaparecer. Essa busca envolve uma intensa perseguição ao poderoso Homem de Preto (Matthew McConaughey), passagens entre tempos diferentes, encontros intensos e confusões entre o real e o imaginário. Baseado na obra literária homônima de Stephen King.', 4);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('O Senhor dos Anéis', 'A Sociedade do Anel', 2001, 'https://www.themoviedb.org/t/p/w1280/2MK3i5CsPuWNwMmgS3ntAcOQhRF.jpg', 'Em uma terra fantástica e única, um hobbit recebe de presente de seu tio um anel mágico e maligno que precisa ser destruído antes que caia nas mãos do mal. Para isso, o hobbit Frodo tem um caminho árduo pela frente, onde encontra perigo, medo e seres bizarros. Ao seu lado para o cumprimento desta jornada, ele aos poucos pode contar com outros hobbits, um elfo, um anão, dois humanos e um mago, totalizando nove pessoas que formam a Sociedade do Anel.', 4);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Harry Potter', 'e a Pedra Filosofal', 2001, 'https://www.themoviedb.org/t/p/w1280/l1FfRmKRNXRSqXT5GlMo16MX2LX.jpg', 'Harry Potter é um garoto órfão que vive infeliz com seus tios, os Dursley. Em seu aniversário de 11 anos ele recebe uma carta que mudará sua vida: um convite para ingressar em Hogwarts.', 5);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Hellraiser', 'Renascido do Inferno', 1987, 'https://www.themoviedb.org/t/p/w1280/gQsqWWy9ezNI2dOmTnICt2SS5Uz.jpg', 'Larry e Julia mudam-se para uma velha casa. Lá, descobrem uma horrível criatura, que na verdade é Frank, meio-irmão de Larry e antigo amante de Julia. Frank perdeu seu corpo humano para os Cenobites, um trio de repulsivos demônios. Uma gota de sangue desperta Frank, que força sua antiga namorada a trazer vítimas para que ele possa novamente reconstituir seu corpo.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Warlock 2','O Armageddon', 1993,'https://www.themoviedb.org/t/p/w1280/qpRtxbnLb0qFP93db5vwDDXvWz2.jpg','O anjo Warlock, filho de Satã, vêm para a Terra à procura de seis pedras mágicas, que juntas, criam o Armageddon. A única força capaz de abrir as portas do inferno. Mas ele não está só. Em seu caminho há dois jovens, os últimos representantes dos sacerdotes Druidas, povo com poderes sobrenaturais.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Ace Ventura 2','Um Maluco na África', 1995,'https://www.themoviedb.org/t/p/w1280/ai9kRyLHUIdmvWKHTl4NSi0Ghsw.jpg','Depois de não conseguir salvar um guaxinim, Ace Ventura (Jim Carrey) impôs a si mesmo um exílio entre monges no Himalaia. Ele acaba deixando seu retiro espiritual para tentar encontrar o grande morcego branco sagrado, que foi prometido como dote a uma princesa de uma tribo africana. Caso o animal não seja recuperado em tempo hábil, uma guerra pode estourar entre tribos rivais.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('George','o Rei da Floresta', 1997,'https://www.themoviedb.org/t/p/w1280/g1I6B0b5b5D1113FFarENIwAWne.jpg','Grupo de gorilas adota criança abandonada na selva após acidente com seus pais. Apesar de ser totalmente atrapalhado, o garoto cresce e torna-se o rei dos animais, levando uma vida calma e monótona, até conhecer a linda Úrsula, a primeira mulher de carne e osso que vê em sua vida. Apaixona-se imediatamente, e resolve acompanhá-la até São Francisco, para aprender os costumes e a cultura do homem branco. Pronto! A confusão está armada.', 2);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Uma Mente Brilhante',null, 2001,'https://www.themoviedb.org/t/p/w1280/8K5W9QnNT7r1V9GuJ5z5KlrROkd.jpg','John Nash (Russell Crowe) é um gênio da matemática que, aos 21 anos, formulou um teorema que provou sua genialidade e o tornou aclamado no meio onde atuava. Mas aos poucos o belo e arrogante Nash se transforma em um sofrido e atormentado homem, que chega até mesmo a ser diagnosticado como esquizofrênico pelos médicos que o tratam. Porém, após anos de luta para se recuperar, ele consegue retornar à sociedade e acaba sendo premiado com o Nobel.', 2);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Bleach: 3','Fade to Black ', 2008,'https://www.themoviedb.org/t/p/w1280/12toLeEq2Q0yBGfgoI9n2U5JJoY.jpg','Alguém que porta uma foice ataca Mayuri, que estava em seu laboratório. Mayuri subitamente fica fora de controle e acaba acertando o painel de controle de seu laboratório. Com isso, toda a Seireitei fica coberta por uma nuvem de partículas espirituais, aprisionando todos os Shinigamis dentro de um casulo.', 5);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Bob Esponja', 'O Incrível Resgate', 2020,  'https://image.tmdb.org/t/p/w533_and_h300_bestv2/wu1uilmhM4TdluKi2ytfz8gidHf.jpg', 'Onde está Gary? Segundo Bob Esponja, Gary foi "caracolstrado" pelo temível Rei Poseidon e levado para a cidade perdida de Atlantic City. Junto a Patrick Estrela, ele sai em uma missão de resgate ao querido amigo, e nesta jornada os dois vão conhecer novos personagens e viver inimagináveis aventuras.', 1);


INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Quem leu o livro se decepcionou com a narativa deste filme.', 1, 1);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Pra quem gosta de terror é um ótimo filme!', 4, 1);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Um gênio pouco compreendido em seu tempo.', 8, 1);